title: "[General] "
body:
  - type: markdown
    attributes:
      value: |
        General question about AssetSync Agent or related to assetsync-agent github project
  - type: textarea
    id: description
    attributes:
      label: Your question
      placeholder: My question
    validations:
      required: true
