title: "[Idea] "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        You have an idea or feature request for AssetSync Agent or related to assetsync-agent github project.
  - type: textarea
    id: description
    attributes:
      label: Your idea
      placeholder: My idea
    validations:
      required: true
