#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  purge)
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
        for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
            proxy-server-plugin proxy2-server-plugin basic-authentication-server-plugin
        do
            rm -f /etc/assetsync-agent/$conf.cfg$ext
        done
    done

    # Cleanup var dir
    rm -rf /var/lib/assetsync-agent

    # remove the configuration file itself
    for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
        proxy-server-plugin proxy2-server-plugin basic-authentication-server-plugin
    do
        rm -f /etc/assetsync-agent/$conf.cfg
    done
    [ -d /etc/assetsync-agent ] && rmdir --ignore-fail-on-non-empty /etc/assetsync-agent

    # and finally clear it out from the ucf database
    if which ucf >/dev/null; then
        for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
            proxy-server-plugin proxy2-server-plugin basic-authentication-server-plugin
        do
            ucf --purge /etc/assetsync-agent/$conf.cfg
        done
    fi
    if which ucfr >/dev/null; then
        for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
            proxy-server-plugin proxy2-server-plugin basic-authentication-server-plugin
        do
            ucfr --purge assetsync-agent /etc/assetsync-agent/$conf.cfg
        done
    fi

    ;;
  *)
    exit 0
    ;;
esac

exit 0
