#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  configure)
    [ -d "/etc/assetsync-agent" ] || mkdir "/etc/assetsync-agent"
    [ -d "/etc/assetsync-agent/conf.d" ] || mkdir "/etc/assetsync-agent/conf.d"
    for conf in agent inventory-server-plugin ssl-server-plugin server-test-plugin \
        proxy-server-plugin proxy2-server-plugin basic-authentication-server-plugin
    do
        ucf /usr/share/assetsync-agent/etc/$conf.cfg /etc/assetsync-agent/$conf.cfg
        ucfr assetsync-agent /etc/assetsync-agent/$conf.cfg
    done
    ;;
esac

exit 0
